name: Build Docker Image
on:
  push:
    branches:
      - 'master'
      - 'prod'
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECR_REPOSITORY_PROD: ${{ secrets.ECR_REPOSITORY_PROD }}

jobs:
  conditional_step:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Check for Dockerfile or package.json changes
        id: check_file_changed
        run: |
          diff=$(git diff --name-only HEAD^ HEAD)
          if echo "$diff" | grep -qE '^(Dockerfile|package\.json)$'; then
            echo "docker_package_changed=true" >> $GITHUB_ENV
          else
            echo "docker_package_changed=false" >> $GITHUB_ENV
          fi

      - name: Build Docker Image
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/prod')
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          DEV_IMAGE_TAG: dev
        run: |
          docker build -t public.ecr.aws/${{ secrets.AWS_ACCOUNT_ID }}/${{ env.ECR_REPOSITORY }}:${{ env.DEV_IMAGE_TAG }} .
          docker images
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
          docker push public.ecr.aws/${{ secrets.AWS_ACCOUNT_ID }}/${{ env.ECR_REPOSITORY }}:${{ env.DEV_IMAGE_TAG }}

  build-dev:
    name: build-dev
    runs-on: ubuntu-latest
    container:
      image:  public.ecr.aws/v1u7p7d8/testing-dev1:dev
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Run prettier and npm build
        run: |
          npm run format:check || true
          npm build
